apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast-spring-statefulset
  labels:
    app: hazelcast-spring
spec:
  replicas: 2
  serviceName: hazelcast-spring-service
  selector:
    matchLabels:
      app: hazelcast-spring
  template:
    metadata:
      labels:
        app: hazelcast-spring
    spec:
      containers:
        - name: hazelcast-spring-container
          image: hazelcast-spring-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5701
          - containerPort: 8080
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-spring-service
spec:
  type: NodePort
  selector:
    app: hazelcast-spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
