= Restore a Cluster from Cloud Storage with Hazelcast Platform Operator
:page-layout: tutorial
:page-product: operator
:page-categories: Cloud Native
:page-lang: go, java, node, python
:page-est-time: 20 mins
:description: Learn how to back up data in Hazelcast maps to cloud storage and restore a cluster from that backup data.

{description}

== Context
In this tutorial, you'll do the following:

- Deploy Hazelcast with persistence enabled.

- Create a Hazelcast map that has persistence enabled.

- Back up all map entries to external storage in the cloud.

- Restart the Hazelcast cluster and restore the backup map entries from the cloud.

== Before you Begin

Before starting this tutorial, make sure that you meet the following prerequisites:

* Up and running https://kubernetes.io/[Kubernetes] cluster
* Kubernetes command-line tool, https://kubernetes.io/docs/tasks/tools/#kubectl[kubectl]
* Deployed xref:operator:ROOT:get-started.adoc[Hazelcast Platform Operator]
* Created blob storage and access credentials in one of the cloud providers: https://aws.amazon.com/s3/[AWS] - https://cloud.google.com/storage/[GCP] - https://azure.microsoft.com/en-us/services/storage/blobs/[Azure]

== Step 1. Start the Hazelcast Cluster

. Create a license secret
+
Create a secret with your link:http://trialrequest.hazelcast.com/[Hazelcast Enterprise License].
+
[source, shell]
----
kubectl create secret generic hazelcast-license-key --from-literal=license-key=<hz-license-key>
----

. Create the Hazelcast Cluster
+
Run the following command to create the Hazelcast cluster with Persistence enabled.
+
[source, shell]
----
kubectl apply -f - <<EOF
include::ROOT:example$/operator-external-backup/hazelcast-persistence.yaml[]
EOF
----
+

. Check the Cluster Status
+
Run the following commands to see the cluster status
+
[source, shell]
----
$ kubectl get hazelcast my-hazelcast
NAME           STATUS    MEMBERS
my-hazelcast   Running   3/3
----
+
[source, shell]
----
$ kubectl get pods -l app.kubernetes.io/instance=my-hazelcast
NAME             READY   STATUS    RESTARTS   AGE
my-hazelcast-0   2/2     Running   0          3m43s
my-hazelcast-1   2/2     Running   0          3m16s
my-hazelcast-2   2/2     Running   0          2m50s
----
+
As you can see from the pod states, the agent container will be deployed with the Hazelcast container in the same Pod. The agent is responsible for backing data up into the external storage.

. Get the Address of the Hazelcast Cluster
+
After verifying that the cluster is `Running` and all the members are ready, run the following command to find the discovery address.

+
[source, shell]
----
$ kubectl get hazelcastendpoint my-hazelcast
NAME               TYPE        ADDRESS
my-hazelcast       Discovery   34.30.60.128:5701
----
+
The `ADDRESS` column displays the external address of your Hazelcast cluster.

== Step 2. Create Persistent Map and Put Data

. Create Persistent Map
+
Run the following command to create the Map resource with Persistence enabled.
+
[source, shell]
----
kubectl apply -f - <<EOF
include::ROOT:example$/operator-external-backup/map-persistence.yaml[]
EOF
----


. Check the Status of the Backup
+
Run the following command to check the status of the map configuration.
+
[source,bash]
----
kubectl get map persistent-map
----
+
The status of the map is displayed in the output.
+
[source,bash]
----
NAME             STATUS
persistent-map   Success
----

. Configure the Hazelcast client to connect to the cluster. [[Configure-Client]]
+
To access all sample clients, clone the following repository:
+
[source, shell]
----
git clone https://github.com/hazelcast-guides/hazelcast-platform-operator-external-backup-restore.git
cd hazelcast-platform-operator-external-backup-restore
----
+
The sample code(excluding CLC) for this tutorial is in the link:https://github.com/hazelcast-guides/hazelcast-platform-operator-external-backup-restore/tree/master/docs/modules/ROOT/examples/operator-external-backup[`docs/modules/ROOT/examples/operator-external-backup`] directory.

+
[tabs]
====

CLC::
+
--
NOTE: Before using CLC, it should be installed in your system. Check the installation instructions for CLC: xref:clc:ROOT:install-clc.adoc[].

Run the following command for adding the cluster config to the CLC.

[source, bash]
----
clc config add hz cluster.name=dev cluster.address=<EXTERNAL-IP>
----
--

Java::
+
--
[source, java]
----
include::ROOT:example$/operator-external-backup/java/src/main/java/com/hazelcast/Main.java[]
----
--

NodeJS::
+
--
[source, javascript]
----
include::ROOT:example$/operator-external-backup/nodejs/client.js[]
----
--

Go::
+
--
[source, go]
----
include::ROOT:example$/operator-external-backup/go/main.go[]
----
--

Python::
+
--
[source, python]
----
include::ROOT:example$/operator-external-backup/python/main.py[]
----
--
.NET::
+
--
[source, cs]
----
include::ROOT:example$/operator-external-backup/dotnet/Program.cs[]
----
--


====
+
. Start the client to fill the map.

+
[tabs]
====

CLC::
+
--
Run the following command to fill a map.

[source, bash]
----
for i in {1..10};
do
   clc -c hz map set --name persistent-map key-$i value-$i;
done
----

Run the following command to check the map size.

[source, bash]
----
clc -c hz map size --name persistent-map
----
--

Java::
+
--
[source, bash]
----
cd java
mvn package
java -jar target/*jar-with-dependencies*.jar fill
----

You should see the following output.

[source, shell]
----
Successful connection!
Starting to fill the map with random entries.
Current map size: 2
Current map size: 3
Current map size: 4
....
....
----
--

NodeJS::
+
--
[source, bash]
----
cd nodejs
npm install
npm start fill
----

You should see the following output.

[source, shell]
----
Successful connection!
Starting to fill the map with random entries.
Current map size: 2
Current map size: 3
Current map size: 4
....
....
----
--

Go::
+
--
[source, bash]
----
cd go
go run main.go fill
----

You should see the following output.

[source, shell]
----
Successful connection!
Starting to fill the map with random entries.
Current map size: 2
Current map size: 3
Current map size: 4
....
....
----
--

Python::
+
--
[source, bash]
----
cd python
pip install -r requirements.txt
python main.py fill
----

You should see the following output.

[source, shell]
----
Successful connection!
Starting to fill the map with random entries.
Current map size: 2
Current map size: 3
Current map size: 4
....
....
----
--
.NET::
+
--
[source, bash]
----
cd dotnet
dotnet build
dotnet run fill
----
[source, shell]
----
Successful connection!
Starting to fill the map with random entries.
Current map size: 2
Current map size: 3
Current map size: 4
....
....
----
--

====

== Step 3. Trigger External Backup

For triggering backup, you need `bucketURI` where backup data will be stored in and `secret` with credentials for accessing the given Bucket URI.

. Create Secret
+
Run one of the following command to create the secret according to the cloud provider you want to backup.

+
[tabs]
====

AWS::
+
--
[source,bash]
----
kubectl create secret generic <external-bucket-secret-name> --from-literal=region=<region> \
	--from-literal=access-key-id=<access-key-id> \
	--from-literal=secret-access-key=<secret-access-key>
----
--

GCP::
+
--
[source,bash]
----
kubectl create secret generic <external-bucket-secret-name> --from-file=google-credentials-path=<service_account_json_file>
----
--

Azure::
+
--
[source,bash]
----
kubectl create secret generic <external-bucket-secret-name> \
	--from-literal=storage-account=<storage-account> \
	--from-literal=storage-key=<storage-key>
----
--

NOTE: If you want to learn more about other authentication methods, check the xref:operator:ROOT:authorization.adoc[Authorization Methods to Access Cloud Storage] documentation.

====

. Trigger Backup
+
Run the following command to trigger backup
+
[source, shell]
----
kubectl apply -f - <<EOF
include::ROOT:example$/operator-external-backup/hot-backup.yaml[]
EOF
----
+
*Example URI -> "s3://operator-backup?prefix=hazelcast/2022-06-08-17-01-20/"*

+
. Check the Status of the Backup
+
Run the following command to check the status of the backup
+
[source,bash]
----
kubectl get hotbackup hot-backup
----
+
The status of the backup is displayed in the output.
+
[source,bash]
----
NAME         STATUS
hot-backup   Success
----

== Step 4. Restore from External Backup

. Delete the Hazelcast Cluster
+
Run the following command to delete the Hazelcast cluster
+
[source,bash]
----
kubectl delete hazelcast my-hazelcast
----

. Delete the PersistentVolumeClaims
+
The data will be restored from external buckets, so you do not keep persistent volumes during restore operation.
+
Run the following command to list PVCs which were created for Hazelcast cluster
+
[source,bash]
----
$ kubectl get pvc -l "app.kubernetes.io/managed-by=hazelcast-platform-operator"
NAME                         STATUS   VOLUME                                     CAPACITY
persistence-my-hazelcast-0   Bound    pvc-a77fcd6e-e64d-4aeb-9708-835d66b4c5b9   8Gi
persistence-my-hazelcast-1   Bound    pvc-8548a4a5-fa8e-45bd-9909-8e6bb6a6c3e8   8Gi
persistence-my-hazelcast-2   Bound    pvc-c94edb25-5a72-482a-bf4e-84a99319d509   8Gi
----

+
Run the following command to delete the PVCs
+
[source,bash]
----
kubectl delete pvc -l "app.kubernetes.io/managed-by=hazelcast-platform-operator"
----

. Create new Hazelcast Cluster
+
For restoring you will use the `HotBackup` resource you have created.
+
Run the following command to create the Hazelcast cluster. Before the Hazelcast cluster is started,
the operator starts the agent(as InitContainer) which restores the backup data from the external bucket.
+
[source, shell]
----
kubectl apply -f - <<EOF
include::ROOT:example$/operator-external-backup/hazelcast-persistence-restore.yaml[]
EOF
----
+
As you may see, the agent configuration is not set. Thus, the operator directly use the latest stable version of the agent.

. Check the Cluster Status
+
Run the following commands to see the cluster status
+
[source, shell]
----
$ kubectl get hazelcast my-hazelcast
NAME           STATUS    MEMBERS
my-hazelcast   Running   3/3
----
+
After verifying that the cluster is `Running` and all the members are ready, run the following command to find the discovery address.
+
[source, shell]
----
$ kubectl get hazelcastendpoint my-hazelcast
NAME           TYPE        ADDRESS
my-hazelcast   Discovery   34.28.159.226:5701
----
+
Since we recreate the Hazelcast cluster, services are also recreated. The `ADDRESS` may change.

. Check the Map Size
+
Configure the Hazelcast client to connect to the cluster external address as you did in <<Configure-Client, Configure the Hazelcast Client>>.
+
Start the client to check the map size and see if the restore is successful.
+
[tabs]
====

CLC::
+
--
[source, bash]
----
clc -c hz map size --name persistent-map
----
--

Java::
+
--
[source, bash]
----
cd java
mvn package
java -jar target/*jar-with-dependencies*.jar size
----

You should see the following output.

[source, shell]
----
Successful connection!
Current map size: 12
----
--

NodeJS::
+
--
[source, bash]
----
cd nodejs
npm install
npm start size
----

You should see the following output.

[source, shell]
----
Successful connection!
Current map size: 12
----
--

Go::
+
--
[source, bash]
----
cd go
go run main.go size
----

You should see the following output.

[source, shell]
----
Successful connection!
Current map size: 12
----
--

Python::
+
--
[source, bash]
----
cd python
pip install -r requirements.txt
python main.py size
----

You should see the following output.

[source, shell]
----
Successful connection!
Current map size: 12
----
--
.NET::
+
--
[source, bash]
----
cd dotnet
dotnet run size
----

You should see the following output.

[source, shell]
----
Successful connection!
Current map size: 12
----
--

====

== Clean Up

To clean up the created resources remove the all Custom Resources and PVCs.

[source, shell]
----
kubectl delete secret <external-bucket-secret-name>
kubectl delete secret hazelcast-license-key
kubectl delete $(kubectl get hazelcast,hotbackup -o name)
kubectl delete pvc -l "app.kubernetes.io/managed-by=hazelcast-platform-operator"
----

== See Also

- xref:operator:ROOT:backup-restore.adoc[]
- xref:hazelcast-platform-operator-expose-externally.adoc[]
