apiVersion: v1
kind: Template
metadata:
  name: hazelcast
  annotations:
    description: "Openshift deployment template for Hazelcast"
    tags: "hazelcast, imdg, datagrid, inmemory, kvstore, nosql, java"
    iconClass: "icon-java"
labels:
    template: hazelcast-openshift-template

parameters:
- name: HAZELCAST_IMAGE
  description: "Defines the location of Hazelcast image"
  value: hazelcast/hazelcast:4.0
  required: true
- name: SERVICE_NAME
  description: "Defines the service name of the POD to lookup of Kubernetes"
  value: hazelcast-service
  required: true
- name: NAMESPACE
  description: "Defines the namespace (project name) of the application POD of Kubernetes"
  required: false
- name: HAZELCAST_REPLICAS
  description: "Number of Hazelcast members"
  value : "3"
  required": true

objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: hazelcast-configuration
  data:
    hazelcast.yaml: |-
      hazelcast:
        network:
          join:
            multicast:
              enabled: false
            kubernetes:
              enabled: true
          rest-api:
            enabled: true
            endpoint-groups:
              HEALTH_CHECK:
                enabled: true

- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: hazelcast
    labels:
      app: hazelcast
  spec:
    replicas: ${HAZELCAST_REPLICAS}
    selector:
      matchLabels:
        app: hazelcast
    template:
      metadata:
        labels:
          app: hazelcast
      spec:
        containers:
        - name: hazelcast-openshift
          image: ${HAZELCAST_IMAGE}
          ports:
          - name: hazelcast
            containerPort: 5701
          livenessProbe:
            httpGet:
              path: /hazelcast/health/node-state
              port: 5701
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /hazelcast/health/node-state
              port: 5701
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
          volumeMounts:
          - name: hazelcast-storage
            mountPath: /data/hazelcast
          env:
          - name: HAZELCAST_KUBERNETES_SERVICE_DNS
            value: ${SERVICE_NAME}.${NAMESPACE}.svc.cluster.local
          - name: JAVA_OPTS
            value: "-Dhazelcast.config=/data/hazelcast/hazelcast.yaml"
        volumes:
        - name: hazelcast-storage
          configMap:
            name: hazelcast-configuration

- apiVersion: v1
  kind: Service
  metadata:
    name: ${SERVICE_NAME}
  spec:
    type: ClusterIP
    clusterIP: None
    selector:
      app: hazelcast
    ports:
    - protocol: TCP
      port: 5701
