services:

  hz1:
    image: hazelcast/hazelcast:5.4.0-SNAPSHOT
    environment:
      JAVA_OPTS: -Dhazelcast.config=/project/hazelcast.yaml
    ports:
      - "5701:5701"
    volumes:
      - ".:/project"
    networks:
      - hznet

  hz2:
    image: hazelcast/hazelcast:5.4.0-SNAPSHOT
    environment:
      JAVA_OPTS: -Dhazelcast.config=/project/hazelcast.yaml
    volumes:
      - ".:/project"
    networks:
      - hznet
    profiles:
      - disabled

  hz3:
    image: hazelcast/hazelcast:5.4.0-SNAPSHOT
    environment:
      JAVA_OPTS: -Dhazelcast.config=/project/hazelcast.yaml
    volumes:
      - ".:/project"
    networks:
      - hznet
    profiles:
      - disabled

  mc:
    image: hazelcast/management-center:5.4.0-BETA-2
    environment:
      MC_DEFAULT_CLUSTER: dev
      MC_DEFAULT_CLUSTER_MEMBERS: hz1:5701
    ports:
      - "8080:8080"
    networks:
      - hznet

  # submit-aggregation-job:
  #   image: hazelcast/hazelcast-enterprise:5.3
  #   volumes:
  #     - ".:/project"
  #   command: >
  #     hz-cli submit 
  #         -v 
  #         -c=hazelcast.platform.labs.machineshop.AggregationPipeline 
  #         -t=dev@hz   
  #         -n=aggregator 
  #         /project/pipelines/target/pipelines-1.0-SNAPSHOT.jar 
  #         redpanda:9092 
  #         machine_events
  #   networks:
  #   - hznet

  # submit-status-service-job:
  #   image: hazelcast/hazelcast-enterprise:5.3
  #   volumes:
  #     - ".:/project"
  #   command: >
  #     hz-cli 
  #         -f /project/config/cli-client.yaml 
  #         submit 
  #         -v 
  #         -c=hazelcast.platform.labs.machineshop.MachineStatusServicePipeline1 
  #         -n=status_service_1
  #         /project/pipelines/target/pipelines-1.0-SNAPSHOT.jar 
  #         machinestatus_v1_request 
  #         machinestatus_response
  #   networks:
  #     - hznet
  #   profiles:
  #     - disabled

  # submit-status-service-job-2:
  #   image: hazelcast/hazelcast-enterprise:5.3
  #   volumes:
  #     - ".:/project"
  #   command: >
  #     hz-cli submit 
  #         -v 
  #         -c=hazelcast.platform.labs.machineshop.MachineStatusServicePipeline2 
  #         -t=dev@hz   
  #         -n=status_service_2
  #         /project/pipelines/target/pipelines-1.0-SNAPSHOT.jar 
  #         machinestatus_v2_request 
  #         machinestatus_response
  #   networks:
  #     - hznet

  refdata-loader:
    image: amazoncorretto:17
    command: java -jar /project/refdata-loader/target/refdata-loader-1.0-SNAPSHOT.jar
    environment:
      HZ_SERVERS: hz1
      HZ_CLUSTER_NAME: dev
      CARD_COUNT: 100000
    volumes:
      - ".:/project"
    networks:
      - hznet

  event-generator:
     build:
       context: event-generator
     command: python /project/event-generator/event_generator.py
     environment:
       HZ_SERVERS: hz1
       HZ_CLUSTER_NAME: dev
       KAFKA_BOOTSTRAP_SERVERS: "redpanda:9092"
       KAFKA_TRANSACTION_TOPIC: "transactions"
     volumes:
       - ".:/project"
     networks:
       - hznet
  
  # ui:
  #   build:
  #     context: ./ui
  #   environment:
  #     HZ_SERVERS: hz
  #     HZ_CLUSTER_NAME: dev
  #   ports:
  #     - "8050:8050"
  #   networks:
  #     - hznet
  #   profiles:
  #     - disabled
  #     # note that the UI will not work on this branch because it expects events in
  #     # the machine_status_events imap

  # status-service:
  #   image: amazoncorretto:21
  #   command: >
  #     java -Dhazelcast.client.config=/project/config/hazelcast-client.yaml 
  #       -jar /project/machine-status-service/target/machine-status-service-1.0-SNAPSHOT.jar
  #   environment:
  #     HZCLIENT_INSTANCENAME: status_service
  #     HZ_SERVERS: hz
  #     HZ_CLUSTER_NAME: dev
  #     hazelcast.pipeline.dispatcher.embed_hazelcast: false
  #     hazelcast.pipeline.dispatcher.request_timeout_ms: 2000
  #   volumes:
  #     - ".:/project"
  #   ports:
  #     - "8888:8080"
  #   networks:
  #     - hznet

  # performance-test:
  #   build:
  #     context: ./performance-test
  #   entrypoint: /project/performance-test/perftest.sh
  #   environment:
  #     HZ_SERVERS: hz
  #     HZ_CLUSTER_NAME: dev
  #   volumes:
  #     - ".:/project"
  #   ports:
  #     - "8089:8089"
  #   networks:
  #     - hznet

  # load-routing-config-1:
  #   image: amazoncorretto:21
  #   command: >
  #     java -cp /project/routing-tools/target/dependency/*
  #          -Dhazelcast.client.config=/project/config/cli-client.yaml 
  #          hazelcast.platform.solutions.pipeline.dispatcher.RoutingConfigTool load 
  #           --input /project/config/routing_1.json
  #   environment:
  #     HZCLIENT_INSTANCENAME: config_tool
  #   volumes:
  #     - ".:/project"
  #   networks:
  #     - hznet
  #   profiles:
  #     - disabled

  # load-routing-config-2:
  #   image: amazoncorretto:21
  #   command: >
  #     java -cp /project/routing-tools/target/dependency/*
  #          -Dhazelcast.client.config=/project/config/cli-client.yaml 
  #          hazelcast.platform.solutions.pipeline.dispatcher.RoutingConfigTool load 
  #          --input /project/config/routing_2.json
  #   environment:
  #     HZCLIENT_INSTANCENAME: config_tool
  #   volumes:
  #     - ".:/project"
  #   networks:
  #     - hznet

  # dump-routing-config:
  #   image: amazoncorretto:21
  #   command: >
  #     java -cp /project/routing-tools/target/dependency/*
  #          -Dhazelcast.client.config=/project/config/hazelcast-client.yaml 
  #          hazelcast.platform.solutions.pipeline.dispatcher.RoutingConfigTool dump 
  #          --output routes.json
  #   environment:
  #     HZCLIENT_INSTANCENAME: config_tool
  #   volumes:
  #     - ".:/project"
  #   networks:
  #     - hznet
  #   profiles:
  #     - disabled

  redpanda:
    image: redpandadata/redpanda:v23.2.12
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092
    networks:
      - hznet

  kafka-ui:
    image: provectuslabs/kafka-ui
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: redpanda:9092
    ports:
      - 8000:8080
    networks:
      - hznet

networks:
  hznet: 
  
