name: build-native
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.adoc'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]
        architecture: [ 'x64' ]

    name: Build Native Executable with JDK ${{ matrix.java }} on ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}

      - name: Maven Build the Native Runner
        run: mvn package && mvn clean package -Pnative -Dquarkus.native.container-build=true

      - name: Build the Native Docker Image
        run: docker build . -f Dockerfile.native -t hazelcast-guides/hazelcast-quarkus

      - name: Launch Application with Hazelcast Cluster
        run: docker-compose up -d

      - name: Verify
        run: |
          echo "Setting key=key_1&value=value_1"
          curl -s -X POST "localhost:8081/hazelcast/put?key=key_1&value=value_1" && sleep 1

          echo
          echo "Retrieving value for key=key_1"
          readonly result="$(curl "localhost:8080/hazelcast/get?key=key_1" | jq -r .value)"
          echo "Retrieved key_1 value: [$result]"
          [[ "$result" = "value_1" ]] || exit 1
