name: build
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.adoc'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]
        architecture: [ 'x64' ]

    name: Build with JDK ${{ matrix.java }} on ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}

      - name: Maven Build
        run: mvn package

      - name: Build the Docker Image
        run: docker build . -f Dockerfile -t hazelcast-guides/hazelcast-quarkus

      - name: Launch Application with Hazelcast Cluster
        run: docker-compose up -d

      - name: Verify
        run: |
          attempts=0
          max_attempts=10
          until $(curl --output /dev/null --silent --head --fail "localhost:8081/hazelcast/get?key=key_1"); do
            if [ ${attempts} -eq ${max_attempts} ];then
                echo "Application not responding"
                exit 1
            fi
            printf '.'
            attempts=$(($attempts+1))
            sleep 1
          done
          echo

          echo "Setting key=key_1&value=value_1"
          curl -s -X POST "localhost:8081/hazelcast/put?key=key_1&value=value_1" && sleep 1

          echo
          echo "Retrieving value for key=key_1"
          readonly result="$(curl "localhost:8080/hazelcast/get?key=key_1" | jq -r .value)"
          echo "Retrieved key_1 value: [$result]"
          [[ "$result" = "value_1" ]] || exit 1
