---
# Service DNS for Management Center will be "hazdb-management-center.default.svc.cluster.local".
---
# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$$$$$$$ SERVICE DEFINITIONS $$$$$$$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
---
# Service for Management Center
---
apiVersion: v1
kind: Service
metadata:
  name: hazdb-management-center
spec:
  selector:
    app: hazdb-management-center
  ports:
    - name: hazdb-management-center
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$$$$$$$$$ POD DEFINITIONS $$$$$$$$$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
---
# Pod for Management Center
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazdb-management-center
spec:
  selector:
    matchLabels:
      app: hazdb-management-center
  template:
    metadata:
      labels:
        app: hazdb-management-center
    spec:
      containers:
        - image: "hazdb/hazelcast-management-center"
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
          name: hazdb-management-center-container
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
---
