name: tf-guide-gcp
on:
  workflow_dispatch:
  push:
    paths:
      - 'gcp/**'
  pull_request:
    paths:
      - 'gcp/**'

jobs:
  build:
    defaults:
      run:
        shell: bash
    env:
      GCP_KEY_FILE: ${{ secrets.GCP_KEY_FILE }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout to repo 
        uses: actions/checkout@v2

      - name : Set-up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.0

      - name: Configure terraform.tfvars
        run: |
          sed -i -e "s~#\"id_rsa\"~\"id_rsa\"~g" gcp/terraform.tfvars
          sed -i -e "s~#\"\~/\.ssh\"~\"\~/\.ssh\"~g" gcp/terraform.tfvars
          project_id=$(echo $GCP_KEY_FILE | grep -Po '"project_id":\s"\K[-a-zA-Z0-9]+')
          sed -i -e "s~#\"project_id\"~\"${project_id}\"~g"  gcp/terraform.tfvars

      - name: Create GCP credentials file
        run: |
          touch gcp/YOUR-KEY-FILE.json
          echo $GCP_KEY_FILE > gcp/YOUR-KEY-FILE.json

      - name: Use unique prefix for resources
        run: |
          sed -i -e "s~\"hazelcast\"~\"${GITHUB_WORKFLOW}-${GITHUB_RUN_ID}\"~g" gcp/terraform.tfvars

      - name: Terraform Init
        run: cd gcp && terraform init

      - name: Terraform Format
        run: cd gcp  && terraform fmt

      - name: Install private key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa 
          known_hosts: " "

      - name: Install public key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PUBLIC_KEY }}
          name: id_rsa.pub 
          known_hosts: " "

      - name: Terraform Apply
        run: |
          cd gcp  && terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ always() }}
        run: |
          cd gcp && terraform destroy -auto-approve
