= Create a Failover Client
:url-code-sample-client-failover: https://github.com/hazelcast-guides/client-failover/blob/master/docs/modules/client-failover/examples/ClientWithSsl.java
:description: In this tutorial, you'll update the code in a Java client to automatically connect to a secondary, failover cluster if it cannot connect to its original, primary cluster. You'll also run a simple test to make sure that your configuration is correct and then adjust it to include exception handling.
:page-layout: tutorial
:page-product: cloud
:page-categories: Fault Tolerance
:page-est-time: 30 mins
:page-lang: java

{description}

== Context

Failover is an important feature of systems that rely on near-constant availability. In Hazelcast, a failover client automatically redirects its traffic to a secondary cluster when the client cannot connect to the primary cluster.

[[step-1-setup]]
== Step 1. Set Up Clusters and Clients

Create two clusters in Hazelcast {hazelcast-cloud} that you'll use as your primary and secondary clusters and then download and connect sample Java clients to them.

. xref:cloud:ROOT:create-serverless-cluster.adoc[Create the {hazelcast-cloud} Standard cluster] that you'll use as your primary cluster. When the cluster is ready to use, the *Quick Connection Guide* is displayed.
. Select the Java icon and follow the on-screen instructions to download, extract, and connect the preconfigured Java client to your primary cluster.
. xref:cloud:ROOT:create-serverless-cluster.adoc[Create the {hazelcast-cloud} Standard cluster] that you'll use as your secondary cluster. 
. Follow the instructions in the *Quick Connection Guide* to download, extract, and connect the preconfigured Java client to your secondary cluster. 

You now have two running clusters, and you've checked that both Java clients can connect.

[[step-2-configuration]]
== Step 2. Configure a Failover Client

To create a failover client, update the configuration and code of the Java client for your primary cluster. 

Start by adding the keystore files from the Java client of your secondary cluster.

.	Go to the directory where you extracted the Java client for your secondary cluster and then navigate to `src/main/resources`.
. Rename the `client.keystore` file to `client2.keystore` and rename the `client.truststore` file to `client2.truststore` to avoid overwriting the files in your primary cluster keystore. 
. Copy both files over to the `src/main/resources` directory of your primary cluster.

Update the code in the Java client (`ClientwithSsl.java`) of your primary cluster to include a failover class and the connection details for your secondary cluster. You can find these connection details in the Java client of your secondary cluster.

. Go to the directory where you extracted the Java client for your primary cluster and then navigate to `src/main/java/com/hazelcast/cloud/`.
. Open the Java client (`ClientwithSsl.java`) and make the following updates. An link:{url-code-sample-client-failover}[example failover client] is also available for download.

.ClientwithSsl.java
[source,java]
----
include::tutorials:client-failover:example$ClientWithSsl.java[tags=!intro-comments]
----
<1> Add import for the `ClientFailoverConfig` class.
<2> Create a `ClientFailoverConfig` object.
<3> For testing purposes, uncomment the `nonStopMapExample(client)` method.
<4> Create the config object for the primary cluster. 
<5> For testing purposes, set `setClusterConnectTimeoutMillis` to `10000` milliseconds or ten seconds. This reduces the timeout period before the failover client tries to connect to an alternative cluster.   
<6> Create the config object for the secondary cluster.
<7> Provide the keystore files for the secondary cluster. 

[[step-3-testing]]
== Step 3. Verify Failover

Check that your failover client automatically connects to the secondary cluster when your primary cluster is stopped.

. Make sure that both {hazelcast-cloud} Standard clusters are running.
. Connect your failover client to the primary cluster in the same way as you did in <<step-1-setup, Step 1>>.
. Stop your primary cluster. From the dashboard of your primary cluster, in *Cluster Details*, select *Pause*. In the console, you'll see the following messages in order as the client disconnects from your primary cluster and reconnects to the secondary cluster:

** `CLIENT_DISCONNECTED`
** `CLIENT_CONNECTED`
** `CLIENT_CHANGED_CLUSTER`  

If you're using the `nonStopMapExample` in the sample Java client, your client stops. This is expected because write operations are not retryable when a cluster is disconnected. The client has sent a put request to the cluster but has not received a response, and so the result of the request is unknown. To prevent the client from overwriting more recent write operations, this write operation is stopped and an exception is thrown. 

[[step-4-exception-handling]]
== Step 4. Exception Handling

Update the `nonStopMapExample()` function in your failover client to trap the exception that is thrown when the primary cluster disconnects.

. Add the following try-catch block to the `while` loop in the `nonStopMapExample()` function. This code replaces the original `map.put()` function.
+
[source,java]
----
try {
    map.put("key-" + randomKey, "value-" + randomKey);
} catch (Exception e) {
    // Captures exception from disconnected client
    e.printStackTrace();
}
----

. <<step-3-testing, Verify your code again>>. This time the client continues to write map entries after it connects to the secondary cluster.

== Summary

In this tutorial, you learned how to do the following:

* Collect all the resources that you need to create a failover client for a primary and secondary cluster.
* Create a failover client based on the sample Java client.
* Test failover.
* Add exception handling for operations that are not retryable.

== Learn More

Use these resources to continue learning:

- xref:cloud:ROOT:wan-replication.adoc[].

- xref:cloud:ROOT:charts-and-stats.adoc[].

- xref:cloud:ROOT:management-center.adoc[].
