apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: my-hazelcast
spec:
  clusterSize: 3
  licenseKeySecretName: hazelcast-license-key
  persistence:
    pvc:
      accessModes: ["ReadWriteOnce"]
      requestStorage: 8Gi
    restore:
      hotBackupResourceName: hot-backup
  exposeExternally:
    type: Unisocket
    discoveryServiceType: LoadBalancer
