{
 "title": "PM : Patient Scorecard",
 "tags": [ "patient_scorecard" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device",
    "query": {}
   },
   {
    "name": "patient",
    "label": "Patient",
    "query": {}
   },
   {
    "name": "id",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Breathing",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "BREATHING.*.$id" }
   ]
  },
  {
   "title": "Consciousness",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "CONSCIOUSNESS.*.$id" }
   ]
  },
  {
   "title": "Heart",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "HEART.*.$id" }
   ]
  },
  {
   "title": "Oxygen Saturation One",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "OXYGEN-SATURATION-ONE.*.$id" }
   ]
  },
  {
   "title": "Oxygen Saturation Two",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "OXYGEN-SATURATION-TWO.*.$id" }
   ]
  },
  {
   "title": "Respiratory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "RESPIRATORY.*.$id" }
   ]
  },
  {
   "title": "Systolic Blood Pressure",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "SYSTOLIC-BLOOD-PRESSURE.*.$id" }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "TEMPERATURE.*.$id" }
   ]
  },
  {
   "title": "RESULTS STREAM - $patient",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "target": "aliasByNode(RESULTS.*.$id, 0)" }
   ]
  },
  {
   "title": "DEVICE STREAM - $patient",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "exclude(aliasByNode(*.*.$id, 0), 'RESULTS')"
    }
   ]
  }
 ]
}