= Calculate the Standard Deviation of Customer Satisfaction Scores
:experimental: true

This is an example of how to use an entry processor to process the customer satisfaction scores that are stored in a map.

TIP: For step-by-step instructions of how to run this app, see the link:https://docs.hazelcast.com/tutorials/compute-standard-deviation[tutorial].

== Quickstart

. Add the required elements for `hazelcast-cloud-maven-plugin` in `cluster-side/pom.xml`:

- `clusterId`: Id of your cluster

- `apiKey`: API key

- `apiSecret`: API secret

. Add the required files to add to `client/src/main/resources`:

- `client.keystore`

- `client.truststore`

. Change into the `cluster-side` directory.

. Upload the cluster-side module to the cluster.
+
```bash
mvn clean package hazelcast-cloud:deploy
```

. Change into the `client` directory.
. Execute the client application.
+
```bash
mvn clean compile exec:java@standard-deviation -Dexec.cleanupDaemonThreads=false
```

== Internal Hazelcast Developers

If you want to try this application in the UAT or DEV environment, edit the `client/src/main/java/your/company/name/ApplicationConfig.java` file to include the environment URL:

```java
// For DEV, use https://test.dev.hazelcast.cloud
clientConfig.setProperty("hazelcast.client.cloud.url", "https://uat.hazelcast.cloud");
```

Then, add the following element to the configuration block for the Hazelcast {hazelcast-cloud} Maven plugin in the `compute/standard-deviation/cluster-side/pom.xml` file. Configure this element with the same environment URL.

```xml
<plugin>
  ...
  <configuration>
    <apiBaseUrl></apiBaseURL>
    ...
  </configuration>
</plugin>
```