# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: card-fraud.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61rd-fraud.proto\"\xdc\x01\n\x0e\x41uthRequestv01\x12\x0e\n\x06gender\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03lat\x18\x04 \x01(\t\x12\x0c\n\x04long\x18\x05 \x01(\t\x12\x10\n\x08\x63ity_pop\x18\x06 \x01(\t\x12\x0b\n\x03job\x18\x07 \x01(\t\x12\x0b\n\x03\x64ob\x18\x08 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\t \x01(\t\x12\x0b\n\x03\x61mt\x18\n \x01(\t\x12\x10\n\x08merchant\x18\x0b \x01(\t\x12\x11\n\tmerch_lat\x18\x0c \x01(\t\x12\x12\n\nmerch_long\x18\r \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'card_fraud_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHREQUESTV01._serialized_start=21
  _AUTHREQUESTV01._serialized_end=241
# @@protoc_insertion_point(module_scope)
