= Synchronize Data between Two Hazelcast Clusters using WAN Sync
:page-layout: tutorial
:page-product: operator
:page-categories: Cloud Native
:page-est-time: 10 mins
:page-lang: go, java, node, python
:description: Learn how to synchronize data across two Hazelcast clusters using WAN Sync.

{description}

== Context
In this tutorial, you'll do the following:

- Deploy two Hazelcast clusters.
- Create a Hazelcast map configuration on one of the clusters.
- Synchronize map data between the two Hazelcast clusters using Full and Delta WAN Sync.

== Before you Begin

Before starting this tutorial, make sure you have the following:

* A running https://kubernetes.io/[Kubernetes] cluster
* The Kubernetes command-line tool, https://kubernetes.io/docs/tasks/tools/#kubectl[kubectl]
* A deployed xref:operator:ROOT:get-started.adoc[Hazelcast Platform Operator]

== Step 1. Start the Hazelcast Clusters

In this step, you'll start two Hazelcast clusters, one called `hazelcast-first` and one called `hazelcast-second`.

. Create a secret with your link:http://trialrequest.hazelcast.com/[Hazelcast Enterprise License].
+
[source, shell]
----
kubectl create secret generic hazelcast-license-key --from-literal=license-key=<hz-license-key>
----

. Start the first Hazelcast cluster.
+
[source, shell]
----
kubectl apply -f - <<EOF
include::ROOT:example$/operator-wan-sync/hazelcast-first.yaml[]
EOF
----

. Check the status of the cluster to ensure it is running.
+
[source, shell]
----
kubectl get hazelcast
----
+
[source, shell]
----
NAME               STATUS    MEMBERS
hazelcast-first    Running   3/3
----

. Start the second cluster

+
[source, shell]
----
kubectl apply -f - <<EOF
include::ROOT:example$/operator-wan-sync/hazelcast-second.yaml[]
EOF
----

. Check the status to ensure that both clusters are running.
+
[source, shell]
----
kubectl get hazelcast
----
+
[source, shell]
----
NAME               STATUS    MEMBERS
hazelcast-first     Running   3/3
hazelcast-second    Running   3/3
----


== Step 2. Create and Populate a Map for WAN Replication

In this step, you will create and populate a map on the `hazelcast-first` cluster. This map will be the source for WAN Replication.

. Create the configuration for a map called `map-sync` on the `hazelcast-first` cluster.
+
If you need *Full WAN Synchronization*, use the following command.
+
[source, shell]
----
kubectl apply -f - <<EOF
include::ROOT:example$/operator-wan-sync/full-sync-map.yaml[]
EOF
----
+
If you need *Delta WAN Synchronization*, use the following command.
+
[source, shell]
----
kubectl apply -f - <<EOF
include::ROOT:example$/operator-wan-sync/delta-sync-map.yaml[]
EOF
----
+
[NOTE]
====
Aren't sure whether you need Full or Delta? See https://docs.hazelcast.com/hazelcast/5.5/wan/advanced-features#synchronizing-wan-target-cluster[Full WAN Synchronization] and https://docs.hazelcast.com/hazelcast/5.5/wan/advanced-features#delta-wan-synchronization[Delta WAN Synchronization] for details.
====

. Find the address of the first cluster.
+
[source, shell]
----
kubectl get hazelcastendpoint --selector="app.kubernetes.io/instance in (hazelcast-first)"
----
+
[source, shell]
----
NAME                   TYPE        ADDRESS
hazelcast-first        Discovery   34.123.9.149:5701
hazelcast-first-wan    WAN         34.123.9.149:5710
----
+
The `ADDRESS` column displays the external address of the first Hazelcast cluster.

. If you want to use a client other than Hazelcast CLC, download the repository for the client code: 
+
[source, shell]
----
git clone https://github.com/hazelcast-guides/hazelcast-platform-operator-wan-sync.git
cd hazelcast-platform-operator-wan-sync
----
+
You will find language-specific client code in the `docs/modules/ROOT/examples/operator-wan-sync` directory. 

. Configure the Hazelcast client to connect to the first cluster using its address. [[configure-client]]

+
[tabs]
====

CLC::
+
--
NOTE: Before using CLC, it should be installed on your system. Check the installation instructions for CLC: xref:clc:ROOT:install-clc.adoc[].

Run the following command to add the first cluster config to the CLC.
[source, bash]
----
clc config add hz-1 cluster.name=dev cluster.address=<FIRST-CLUSTER-EXTERNAL-IP>
----
--

Java::
+
--
[source, java]
----
include::ROOT:example$/operator-wan-sync/java/src/main/java/com/hazelcast/Main.java[]
----
--

NodeJS::
+
--
[source, javascript]
----
include::ROOT:example$/operator-wan-sync/nodejs/client.js[]
----
--

Go::
+
--
[source, go]
----
include::ROOT:example$/operator-wan-sync/go/main.go[]
----
--

Python::
+
--
[source, python]
----
include::ROOT:example$/operator-wan-sync/python/main.py[]
----
--
.NET::
+
--
[source, cs]
----
include::ROOT:example$/operator-wan-sync/dotnet/Program.cs[]
----
--

====

. Add entries to the map.
+
[tabs]
====

CLC::
+
--
Execute the following command to populate the map with entries, replacing `<MAP-NAME>` with the actual map name, `map-sync`.

[source, bash]
----
for i in {1..10};
do
   clc -c hz-1 map set --name <MAP-NAME> key-$i value-$i;
done
----

Verify that the map has the expected number of entries. 

[source, bash]
----
clc -c hz-1 map size --name <MAP-NAME>
----
--

Java::
+
--
Start the application to populate the map with entries, replacing `<MAP-NAME>` with the actual map name, `map-sync`.

[source, bash]
----
cd java
mvn package
java -jar target/*jar-with-dependencies*.jar fill <MAP-NAME>
----

You should see the following output.

[source, shell]
----
Successful connection!
Starting to fill the map (<MAP-NAME>) with random entries.
Current map size: 2
Current map size: 3
Current map size: 4
....
....
----
--

NodeJS::
+
--
Start the application to populate the map with entries, replacing `<MAP-NAME>` with the actual map name, `map-sync`.

[source, bash]
----
cd nodejs
npm install
npm start fill <MAP-NAME>
----

You should see the following output.

[source, shell]
----
Successful connection!
Starting to fill the map (<MAP-NAME>) with random entries.
Current map size: 2
Current map size: 3
Current map size: 4
....
....
----
--

Go::
+
--
Start the application to populate the map with entries, replacing `<MAP-NAME>` with the actual map name, `map-sync`.

[source, bash]
----
cd go
go run main.go fill <MAP-NAME>
----

You should see the following output.

[source, shell]
----
Successful connection!
Starting to fill the map (<MAP-NAME>) with random entries.
Current map size: 2
Current map size: 3
Current map size: 4
....
....
----
--

Python::
+
--
Start the application to populate the map with entries, replacing `<MAP-NAME>` with the actual map name, `map-sync`.

[source, bash]
----
cd python
pip install -r requirements.txt
python main.py fill <MAP-NAME>
----

You should see the following output.

[source, shell]
----
Successful connection!
Starting to fill the map (<MAP-NAME>) with random entries.
Current map size: 2
Current map size: 3
Current map size: 4
....
....
----
--

.NET::
+
--
Start the application to populate the map with entries, replacing `<MAP-NAME>` with the actual map name, `map-sync`.

[source, bash]
----
cd dotnet
dotnet build
dotnet run fill <MAP-NAME>
----

You should see the following output.

[source, shell]
----
Successful connection!
Starting to fill the map (<MAP-NAME>) with random entries.
Current map size: 2
Current map size: 3
Current map size: 4
....
....
----
--

====

== Step 3. Enable WAN Replication and Replicate Entries

In this step, you'll first verify that the second cluster does not contain a `map-sync` structure. You'll then enable WAN Replication and verify that the map and all entries have been copied to the second cluster. 

. Find the address of the second cluster.
+
[source, shell]
----
kubectl get hazelcastendpoint --selector="app.kubernetes.io/instance in (hazelcast-second)"
----
+
[source, shell]
----
NAME                   TYPE        ADDRESS
hazelcast-second       Discovery   34.16.0.16:5701
hazelcast-second-wan   WAN         34.16.0.16:5710
----
+
The `ADDRESS` column displays the external address of the second Hazelcast cluster.

. Repeat steps 2.3 to 2.4, using the address of the second cluster to enable the client to connect. 

. Connect to the second cluster and verify that the map named `map-sync` contains no data.

+
[tabs]
====

CLC::
+
--
[source, bash]
----
clc -c hz-2 map size --name <MAP-NAME>
----
--

Java::
+
--
[source, bash]
----
cd clients/java
mvn package
java -jar target/*jar-with-dependencies*.jar size <MAP-NAME>
----

You should see the following output:

[source, shell]
----
Successful connection!
Current map (<MAP-NAME>) size: 0
----
--

NodeJS::
+
--
[source, bash]
----
cd clients/nodejs
npm install
npm start size <MAP-NAME>
----

You should see the following output:

[source, shell]
----
Successful connection!
Current map (<MAP-NAME>) size: 0
----
--

Go::
+
--
[source, bash]
----
cd clients/go
go run main.go size <MAP-NAME>
----

You should see the following output:

[source, shell]
----
Successful connection!
Current map (<MAP-NAME>) size: 0
----
--

Python::
+
--
[source, bash]
----
cd clients/python
pip install -r requirements.txt
python main.py size <MAP-NAME>
----

You should see the following output:

[source, shell]
----
Successful connection!
Current map (<MAP-NAME>) size: 0
----
--
.NET::
+
--
[source, bash]
----
cd clients/dotnet
dotnet build
dotnet run size <MAP-NAME>
----

You should see the following output:

[source, shell]
----
Successful connection!
Current map (<MAP-NAME>) size: 0
----
--

====

. Modify the configuration of the first cluster to add the address of the second cluster as the WAN Replication event target. 
+
If you need a *Full WAN Sync*, run the following command to apply the configuration.
+
[source, shell]
----
kubectl apply -f - <<EOF
include::ROOT:example$/operator-wan-sync/full-sync-wanreplication.yaml[]
EOF
----
If you need a *Delta WAN Sync*, run the following command to apply the configuration.
+
[source, shell]
----
kubectl apply -f - <<EOF
include::ROOT:example$/operator-wan-sync/delta-sync-wanreplication.yaml[]
EOF
----

. Create a WAN Sync resource within the Kubernetes cluster, using the existing `WanReplication` CR.
+
[source, shell]
----
kubectl apply -f - <<EOF
include::ROOT:example$/operator-wan-sync/wansync.yaml[]
EOF
----
+
[NOTE]
====
WAN Sync ensures data consistency between the two Hazelcast clusters. Full WAN Sync transmits all data from the source cluster to the target cluster, aligning the state of the target `IMap` with the source `IMap`. This method is particularly beneficial when the synchronization between two remote clusters is lost due to WAN queue overflows or cluster restarts.
====

. Run the following command to see the WAN synchronization status:
+
[source, shell]
----
kubectl get wansync wan-sync
----
+
The output should be similar to the following:
+
[source, shell]
----
NAME       STATUS
wan-sync   Completed
----

. Repeat step 3.3 to verify that the `map-sync` structure on the `hazelcast-second` cluster now contains data. 

== Clean Up

To remove all custom resources, run the following commands:

[source, shell]
----
kubectl delete secret hazelcast-license-key
kubectl delete $(kubectl get wansync,wanreplications,map,hazelcast -o name)
----

== See Also

- xref:operator:ROOT:wan-replication.adoc[]
- xref:hazelcast-platform-operator-expose-externally.adoc[]
