== Prerequisites

Before you begin, have the following tools installed:

First, you will need Apache Maven to build and run the project.

Also you will need a containerization software for building containers. {kube} supports a variety
of container types. You will use `Docker` in this guide. For installation instructions, refer to the https://docs.docker.com/install/[official Docker documentation^].

****
[system]#*Windows* | *Mac*#

Use Docker Desktop, where a local {kube} environment is pre-installed and enabled. If you do not see the {kube} tab then you have an older version of Docker Desktop; upgrade to the latest version.

Complete the setup for your operating system:

 - Set up  https://docs.docker.com/docker-for-windows/#kubernetes[Docker for Windows^]. 
 On the Docker for Windows _General Setting_ page, ensure that the option `Expose daemon on 
 tcp://localhost:2375 without TLS` is enabled. This is required by the `dockerfile-maven` 
 part of the build.
 - Set up https://docs.docker.com/docker-for-mac/#kubernetes[Docker for Mac^].

- After following one of the sets of instructions, ensure that {kube} (not Swarm) is selected as the orchestrator in Docker Preferences.

[system]#*Linux*#

You will use `Minikube` as a single-node {kube} cluster that runs locally in a virtual machine.
For Minikube installation instructions see the https://github.com/kubernetes/minikube#installation[minikube installation instructions^]. Make sure to pay attention to the requirements as they vary by platform.

****
