name: tf-guide-azure
on:
  workflow_dispatch:
  push:
    paths:
      - 'azure/**'
  pull_request:
    paths:
      - 'azure/**'

jobs:
  build:
    defaults:
      run:
        shell: bash
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout to repo 
        uses: actions/checkout@v2

      - name : Set-up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.0

      - name: Configure terraform.tfvars
        run: |
          sed -i -e "s~#\"id_rsa\"~\"id_rsa\"~g" azure/terraform.tfvars
          sed -i -e "s~#\"\~/\.ssh\"~\"\~/\.ssh\"~g" azure/terraform.tfvars

      - name: Use unique prefix for resources
        run: |
          sed -i -e "s~\"hazelcast\"~\"${GITHUB_WORKFLOW}-${GITHUB_RUN_ID}\"~g" azure/terraform.tfvars

      - name: Terraform Init
        run: cd azure && terraform init

      - name: Terraform Format
        run: cd azure  && terraform fmt

      - name: Install private key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa 
          known_hosts: " "

      - name: Install public key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PUBLIC_KEY }}
          name: id_rsa.pub 
          known_hosts: " "

      - name: Terraform Apply
        run: |
          cd azure  && terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ always() }}
        run: |
          cd azure && terraform destroy -auto-approve
